package com.cpb.news.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cpb.news.entity.NewsChannel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEWS_CHANNEL".
*/
public class NewsChannelDao extends AbstractDao<NewsChannel, String> {

    public static final String TABLENAME = "NEWS_CHANNEL";

    /**
     * Properties of entity NewsChannel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Type = new Property(2, String.class, "type", false, "TYPE");
        public final static Property IsSelect = new Property(3, boolean.class, "isSelect", false, "IS_SELECT");
        public final static Property Index = new Property(4, int.class, "index", false, "INDEX");
        public final static Property IsFixed = new Property(5, Boolean.class, "isFixed", false, "IS_FIXED");
    }


    public NewsChannelDao(DaoConfig config) {
        super(config);
    }
    
    public NewsChannelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEWS_CHANNEL\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"TYPE\" TEXT NOT NULL ," + // 2: type
                "\"IS_SELECT\" INTEGER NOT NULL ," + // 3: isSelect
                "\"INDEX\" INTEGER NOT NULL ," + // 4: index
                "\"IS_FIXED\" INTEGER);"); // 5: isFixed
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEWS_CHANNEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NewsChannel entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getType());
        stmt.bindLong(4, entity.getIsSelect() ? 1L: 0L);
        stmt.bindLong(5, entity.getIndex());
 
        Boolean isFixed = entity.getIsFixed();
        if (isFixed != null) {
            stmt.bindLong(6, isFixed ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NewsChannel entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getType());
        stmt.bindLong(4, entity.getIsSelect() ? 1L: 0L);
        stmt.bindLong(5, entity.getIndex());
 
        Boolean isFixed = entity.getIsFixed();
        if (isFixed != null) {
            stmt.bindLong(6, isFixed ? 1L: 0L);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public NewsChannel readEntity(Cursor cursor, int offset) {
        NewsChannel entity = new NewsChannel( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getString(offset + 2), // type
            cursor.getShort(offset + 3) != 0, // isSelect
            cursor.getInt(offset + 4), // index
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // isFixed
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NewsChannel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setType(cursor.getString(offset + 2));
        entity.setIsSelect(cursor.getShort(offset + 3) != 0);
        entity.setIndex(cursor.getInt(offset + 4));
        entity.setIsFixed(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(NewsChannel entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(NewsChannel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NewsChannel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
